organizma: Doku.o Hucre.o main.o Organ.o Organizma.o Radix.o Sistem.o IkiliAramaAgaci.o Split.o
	g++ Doku.o Hucre.o main.o Organ.o Organizma.o Radix.o Sistem.o IkiliAramaAgaci.o Split.o -o organizma

Doku.o: Doku.cpp
	g++ -c Doku.cpp

Hucre.o: Hucre.cpp
	g++ -c Hucre.cpp

main.o: main.cpp
	g++ -c main.cpp

Organ.o: Organ.cpp
	g++ -c Organ.cpp

Organizma.o: Organizma.cpp
	g++ -c Organizma.cpp

Radix.o: Radix.cpp
	g++ -c Radix.cpp

Sistem.o: Sistem.cpp
	g++ -c Sistem.cpp

IkiliAramaAgaci.o: IkiliAramaAgaci.cpp
	g++ -c IkiliAramaAgaci.cpp

Split.o: Split.cpp
	g++ -c Split.cpp

clean:
	rm -f *.o organizma