organizma: Doku.o Hucre.o main.o Organ.o Organizma.o radixSort.o Sistem.o BinarySearchTree.o
	g++ Doku.o Hucre.o main.o Organ.o Organizma.o radixSort.o Sistem.o BinarySearchTree.o -o organizma

Doku.o: Doku.cpp
	g++ -c Doku.cpp

Hucre.o: Hucre.cpp
	g++ -c Hucre.cpp

main.o: main.cpp
	g++ -c main.cpp

Organ.o: Organ.cpp
	g++ -c Organ.cpp

Organizma.o: Organizma.cpp
	g++ -c Organizma.cpp

radixSort.o: radixSort.cpp
	g++ -c radixSort.cpp

Sistem.o: Sistem.cpp
	g++ -c Sistem.cpp

BinarySearchTree.o: BinarySearchTree.cpp
	g++ -c BinarySearchTree.cpp

clean:
	rm -f *.o organizma